interval: 5           # seconds between checks
min_brightness: 10    # minimum hardware brightness (0-100)
max_brightness: 90    # maximum hardware brightness (0-100)
threshold: 8          # minimum change to trigger adjustment
use_center: True      # analyze only center region for brightness
monitors: [0, 2]      # monitor indices to adjust
